### ISSUE TITLE
transformer for OrdinationFormat --> metadata

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-types#123] opened 2017-06-02 18:55 UTC
This would be useful to use principal coordinates (or other ordination results) as input metadata. I am working on some methods that could employ this, e.g., to test whether samples change over PC1 before/after treatment.

The transformation of OrdinationFormat --> pd.DataFrame can be achieved with something like this (in a jupyter notebook, at least. I suppose the first line might be unnecessary in a transformer):
```
beta_div = beta_div.view(skbio.OrdinationResults)
beta_div = beta_div.samples.loc[:, 0:2]
beta_div.columns = ['unweighted-unifrac-pc1', 'unweighted-unifrac-pc2', 'unweighted-unifrac-pc3']
```
and then I assume the `beta_div` DataFrame can be converted to metadata with
```
qiime2.Metadata(beta_div)
```
I would find this extremely useful — any interest?

**Comment by ebolyen** [comment] 2017-06-02 21:58
It would be `qiime2.Metadata.from_artifact(beta_div)` (if you wanted to preserve provenance), but yeah!

We're about to write a whole ton of transformers for `FeatureData[...]`, I don't see why this couldn't be added to the list.

@ElDeveloper, does this kind of view make sense to you?

**Comment by thermokarst** [comment] 2017-06-05 15:38
Duplicate of #122, moving discussion into there.

**Closed by thermokarst** 2017-06-05 15:38 UTC
